### ISSUE TITLE
Sample test : launcher bar issue bug created under below link, on entering new bug.

### ISSUE THREAD

**Issue by ramyavscode** [webosose/webos-studio#10]
Type: <b>Bug</b>

Sample test : launcher bar issue bug created under below link, on entering new bug.

Extension version: 2.2.0-beta.6
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:11:49.843Z)
OS version: Linux x64 5.15.0-94-generic
Modes:

**Comment by heegoo-han** [comment]
test only
