### ISSUE TITLE
readme calling wrong package webos-sdk/cli

### ISSUE THREAD

**Issue by poeggi** [webosose/webos-studio#11]
readme mentions manually installing:

npm install -g @enact/cli @webos-sdk/cli patch-package

This is wrong, webos-sdk/cli does not exist.

@webos-tools/cli

would be correct.

**Comment by YoungeunKim** [comment]
Dear @poeggi,

This repository deprecated and moved to @webos-tools/webos-studio. 
(This notice is in @webosose/webos-studio's README : https://github.com/webosose/webos-studio?tab=readme-ov-file#webos-studio) 

![image](https://github.com/user-attachments/assets/63b2ce93-b0a1-4095-b909-9e08eafa31df)



Please refer to the README in https://github.com/webos-tools/webos-studio. 
The README guides to install "@webos-tools/cli" as you mentioned.

![image](https://github.com/user-attachments/assets/77d74c09-7375-498a-a4f5-96e512ad8f28)


Thank you.
cc : @SeongCheolHeo
